name: Flutter APK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu al
        uses: actions/checkout@v3

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Proje klasörüne geç
        run: cd $GITHUB_WORKSPACE

      - name: pubspec kontrol
        run: |
          echo "Bulunan dosyalar:"
          ls -R .

      - name: Paketleri yükle
        run: flutter pub get

      - name: APK üret
        run: flutter build apk --release

      - name: APK’yı yükle
        uses: actions/upload-artifact@v4
        with:
          name: BabilAnaliz_APK
          path: build/app/outputs/flutter-apk/app-release.apk