name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v3

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter paketlerini yükle
        run: flutter pub get

      - name: Keystore olmadan debug apk oluştur
        run: flutter build apk --debug

      - name: APK'yı yükle
        uses: actions/upload-artifact@v3
        with:
          name: BabilAnaliz-APK
          path: build/app/outputs/flutter-apk/app-debug.apk